name: Earthly Setup

inputs:
  version:
    description: The version of Earthly to use
    required: false
    default: 0.8.4

runs:
  using: composite
  steps:
  - uses: actions/cache/restore@v3
    with:
      path: /usr/local/bin/earthly
      key: earthly-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

  - id: system
    shell: bash
    run: |
      os=$(uname -s | tr '[:upper:]' '[:lower:]')
      arch=$(uname -m)
      case $arch in
        x86_64) arch=amd64 ;;
        aarch64) arch=arm64 ;;
      esac

      echo os=$os >> "$GITHUB_OUTPUT"
      echo arch=$arch >> "$GITHUB_OUTPUT"

  - name: Install Earthly
    shell: bash
    run: |
      if command -v earthly 2>/dev/null && earthly --version | grep -q "earthly version v${{ inputs.version }}"; then
        echo "Earthly version ${version} is already installed"
        exit 0
      fi

      curl -sSfL "https://github.com/earthly/earthly/releases/download/v${{ inputs.version }}/earthly-${{ steps.system.outputs.os }}-${{ steps.system.outputs.arch }}" -o /usr/local/bin/earthly
      chmod +x /usr/local/bin/earthly

      earthly --version

  - name: Configure Earthly
    shell: bash
    run: |
      earthly config global.disable_analytics true
      earthly config global.disable_log_sharing true

  - name: Bootstrap Earthly
    shell: bash
    run: |
      earthly bootstrap

  - uses: actions/cache/save@v3
    with:
      path: /usr/local/bin/earthly
      key: earthly-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}
