name: Earthly

inputs:
  path:
    description: The directory containing Earthfile
    required: false
  target:
    description: The target to run
    required: true
  build-args:
    description: Additional build arguments
    required: false
  push:
    description: Push the image to the registry
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
  - name: Run Earthly build
    shell: bash
    run: |
      build_args="$(echo "${{ inputs.build-args }}" | tr '[:space:]' '\n' | sed -E 's/(^|^--)/--/' | tr '\n' ' ')"
      earthly ${{ inputs.push == 'true' && '--push ' || ''}}${{ inputs.path }}+${{ inputs.target }} $build_args
