name: Earthly

inputs:
  path:
    description: The directory containing Earthfile
    required: false
  target:
    description: The target to run
    required: true
  build-args:
    description: Additional build arguments
    required: false
  platforms:
    description: The platform to build for
    required: false
  push:
    description: Push the image to the registry
    type: boolean
    required: false
    default: false
  no-cache:
    description: Do not use cache while building
    type: boolean
    required: false
    default: false
  use-inline-cache:
    description: Attempt to use any inline cache that may have been previously pushed uses image tags referenced by SAVE IMAGE --push or SAVE IMAGE --cache-from
    type: boolean
    required: false
    default: false
  save-inline-cache:
    description: Enable cache inlining when pushing images
    type: boolean
    required: false
    default: false
  cache-from:
    description: Use the cache from the specified image
    required: false
  remote-cache:
    description: Use the remote cache
    required: false
  max-remote-cache:
    description: Saves all intermediate images too in the remote cache
    type: boolean
    required: false
    default: false
  extra-args:
    description: Additional arguments to pass to Earthly
    required: false
  earthly-version:
    description: The version of Earthly to use
    required: false
    default: ^0.8.0
  github-token:
    description: The GitHub token used to fetch Earthly version
    required: false

runs:
  using: composite
  steps:
  - name: Set up Earthly
    uses: earthly/actions-setup@v1
    with:
      github-token: ${{ inputs.github-token }}
      version: ${{ inputs.earthly-version }}
  - name: Configure Earthly
    shell: bash
    run: |
      earthly config global.disable_analytics true
      earthly config global.disable_log_sharing true
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3
    if: ${{ inputs.platforms != '' }}
    with:
      platforms: ${{ inputs.platforms }}
  - name: Prepare Earthly arguments
    id: earthly-args
    shell: bash
    run: |-
      # Set up Earthly arguments
      echo "${{ inputs.push == 'true' && ' --push ' || ''}}" >> /tmp/earthly-args
      echo "${{ inputs.no-cache == 'true' && ' --no-cache ' || ''}}" >> /tmp/earthly-args
      echo "${{ inputs.use-inline-cache == 'true' && ' --use-inline-cache ' || ''}}" >> /tmp/earthly-args
      echo "${{ inputs.save-inline-cache == 'true' && ' --save-inline-cache ' || ''}}" >> /tmp/earthly-args
      echo "${{ inputs.remote-cache != 'true' && format(' --remote-cache {0}', inputs.remote-cache) || ''}}" >> /tmp/earthly-args
      echo "${{ inputs.max-remote-cache == 'true' && ' --max-remote-cache ' || ''}}" >> /tmp/earthly-args
      echo "${{ inputs.cache-from }}" | tr '\n, ' '\n' | xargs -I{} echo '--cache-from {}' >> /tmp/earthly-args
      echo "${{ inputs.path }}+${{ inputs.target }}" >> /tmp/earthly-args
      echo "${{ inputs.extra-args }}" >> /tmp/earthly-args
      echo "${{ inputs.build-args }}" | tr '[:space:]' '\n' | sed -E 's/(^|^--)/--/' >> /tmp/earthly-args
      echo "args=$(cat /tmp/earthly-args | sed -i '/^$/d' filename | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
  - name: Run Earthly build
    shell: bash
    run: |
      earthly ${{ steps.earthly-args.outputs.args }}
