name: Earthly

inputs:
  path:
    description: The directory containing Earthfile
    required: false
  target:
    description: The target to run
    required: true
  build-args:
    description: Additional build arguments
    required: false
  platforms:
    description: The platform to build for
    required: false
  push:
    description: Push the image to the registry
    type: boolean
    required: false
    default: false
  earthly-version:
    description: The version of Earthly to use
    required: false
    default: ^0.8.0
  github-token:
    description: The GitHub token
    required: false

runs:
  using: composite
  steps:
  - uses: earthly/actions-setup@v1
    with:
      github-token: ${{ inputs.github-token }}
      version: ${{ inputs.earthly-version }}
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3
    if: ${{ inputs.platforms != '' }}
    with:
      platforms: ${{ inputs.platforms }}
  - name: Run Earthly build
    shell: bash
    run: |
      build_args="$(echo "${{ inputs.build-args }}" | tr '[:space:]' '\n' | sed -E 's/(^|^--)/--/' | tr '\n' ' ')"
      earthly ${{ inputs.push == 'true' && '--push ' || ''}}${{ inputs.path }}+${{ inputs.target }} $build_args
